name: kite_admin
description: kite_admin

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  dio: ^4.0.4
  flash: ^2.0.3+2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.3.1
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  image_picker: ^0.8.4+11
  intl: ^0.17.0
  mobile_scanner: ^1.0.0
  shared_preferences: ^2.0.13
  universal_platform: ^1.0.0+1
  url_launcher: ^6.0.20
  webview_flutter: ^3.0.0
  json_serializable: ^6.1.3   # JSON
  json_annotation: ^4.4.0     # JSON code generation

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.7

flutter:
  uses-material-design: true

